server {
    listen 80;

    #Directorio donde nginx buscara los archivos construidos (dist)
    root /usr/share/nginx/html;
    index index.html;

    # Configuración esencial para Single Page Applications (SPA) como React
    # Si entras a /login o /perfil, Nginx intentará buscar ese archivo.
    # Como no existe (todo es virtual en React), le decimos:
    # "Si no encuentras el archivo, carga index.html y deja que React se encargue".
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Opcional: Caché para archivos estáticos (imágenes, css, js)
    location ~* \.(?:ico|css|js|gif|jpe?g|png)$ {
        expires 1y;
        add_header Cache-Control "public";
    }

}